esphome:
  name: thermalprinter
  friendly_name: thermalprinter

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  on_client_connected:
    - logger.log: "=== Home Assistant CONNECTED - Device ready for thermal printer testing ==="
  on_client_disconnected:
    - logger.log: "Home Assistant disconnected"
  services:
    # qrcode: String data to encode (max ~100 characters recommended for reliability)
    - service: print_qrcode
      variables:
        qrcode: string
      then:
        - m5stack_printer.print_qrcode:
            qrcode: !lambda "return qrcode;"
    # Print 1D barcodes with validation
    # barcode: String data for the barcode (content varies by type)
    # type: Barcode format - UPC_A (11-12 digits), UPC_E (11-12 digits), EAN13 (12-13 digits),
    #       EAN8 (7-8 digits), CODE39 (alphanumeric + special), ITF (even digits only),
    #       CODABAR (digits + A-D), CODE93 (full ASCII), CODE128 (full ASCII)
    - service: print_barcode
      variables:
        barcode: string
        type: string
      then:
        - m5stack_printer.print_barcode:
            barcode: !lambda "return barcode;"
            type: !lambda "return type;"
    # Simple text printing without any formatting (for debugging)
    - service: print_simple_text
      variables:
        text_to_print: string
      then:
        - m5stack_printer.print_text:
            text: !lambda "return text_to_print;"
            font_width: 1
            font_height: 1
    # Add line breaks to advance paper
    # lines: Number of lines to advance (1-255)
    - service: new_line
      variables:
        lines: int
      then:
        - m5stack_printer.new_line:
            lines: !lambda "return lines;"
    # Print text with comprehensive styling control (applies styles then prints)
    # text: String to print
    # font_width: Font width multiplier (1-8)
    # font_height: Font height multiplier (1-8)  
    # bold: Enable bold/emphasized text (true/false)
    # double_strike: Enable double-strike mode - overlapping dots for darker text (true/false)
    # underline: Underline mode (0=off, 1=single line, 2=double line)
    # upside_down: Rotate text 180 degrees (true/false)
    # rotation: Enable 90-degree clockwise rotation (true/false)
    # inverse: Enable white text on black background (true/false)
    # chinese_mode: Enable Chinese/Japanese multi-byte character support (true/false)
    # alignment: Text alignment (0=left, 1=center, 2=right)
    # charset: International character set (0-15: 0=USA, 1=France, 2=Germany, etc.)
    # codepage: Character code table (0-47: 0=CP437, 1=Katakana, 2=CP850, etc.)
    # character_spacing: Right-side character spacing (0-255, in 0.125mm units)
    # line_spacing: Custom line spacing in dots (0-255, default ~30)
    # print_density: Print darkness level (0-31, higher=darker, default ~15)
    # break_time: Break time between dots in μs (0-7, affects print speed vs quality)
    - service: print_text
      variables:
        text_to_print: string
        font_width: int
        font_height: int
        font_type: int
        bold: bool
        double_strike: bool
        underline: int
        upside_down: bool
        rotation: bool
        inverse: bool
        chinese_mode: bool
        alignment: int
        charset: int
        codepage: int
        character_spacing: int
      then:
        # Use the comprehensive formatting function that handles all parameters
        - esphome.thermalprinter_print_text:
            text_to_print: !lambda "return text_to_print;"
            font_width: !lambda "return font_width;"
            font_height: !lambda "return font_height;"
            font_type: !lambda "return font_type;"
            bold: !lambda "return bold;"
            double_strike: !lambda "return double_strike;"
            underline: !lambda "return underline;"
            upside_down: !lambda "return upside_down;"
            rotation: !lambda "return rotation;"
            inverse: !lambda "return inverse;"
            chinese_mode: !lambda "return chinese_mode;"
            alignment: !lambda "return alignment;"
            charset: !lambda "return charset;"
            codepage: !lambda "return codepage;"
            character_spacing: !lambda "return character_spacing;"

    # Character set and code page test service
    # charset: 0=USA, 1=France, 2=Germany, 3=UK, 4=Denmark, 5=Sweden, 6=Italy, 7=Spain, 8=Japan, 9=Norway, etc. (0-15)
    # codepage: 0=CP437, 1=Katakana, 2=CP850, 3=CP860, 4=CP863, 5=CP865, etc. (0-47)
    - service: test_character_sets
      then:
        - esphome.thermalprinter_print_text:
            text_to_print: "=== Character Set Test ==="
            alignment: 1
        - esphome.thermalprinter_print_text:
            text_to_print: "USA charset: Hello [@#$%]"
            charset: 0
        - esphome.thermalprinter_print_text:
            text_to_print: "France charset: Bonjour [@#$%]"
            charset: 1
        - esphome.thermalprinter_print_text:
            text_to_print: "Germany charset: Hallo [@#$%]"
            charset: 2
        - esphome.thermalprinter_print_text:
            text_to_print: "CP437 codepage: └┴┐│┤"
            codepage: 0
        - esphome.thermalprinter_print_text:
            text_to_print: "CP850 codepage: çüéâä"
            codepage: 2

    # Character spacing test service
    # Tests different character spacing levels from 0 (normal) to maximum
    # character_spacing: 0-255 units, each unit = 0.125mm extra spacing between characters
    - service: test_character_spacing
      then:
        - esphome.thermalprinter_print_text:
            text_to_print: "=== Character Spacing Test ==="
            alignment: 1
        - esphome.thermalprinter_print_text:
            text_to_print: "Normal spacing (0): HELLO WORLD"
            character_spacing: 0
        - esphome.thermalprinter_print_text:
            text_to_print: "Small spacing (8): H E L L O  W O R L D"
            character_spacing: 8
        - esphome.thermalprinter_print_text:
            text_to_print: "Medium spacing (16): H  E  L  L  O"
            character_spacing: 16
        - esphome.thermalprinter_print_text:
            text_to_print: "Large spacing (32): H   E   L   L   O"
            character_spacing: 32
        - esphome.thermalprinter_print_text:
            text_to_print: "Max spacing (255): A          B"
            character_spacing: 255
        - esphome.thermalprinter_print_text:
            text_to_print: "Test complete - spacing reset to 0"
            character_spacing: 0

    # Double-strike test service  
    # Tests double-strike mode (ESC G n) - overlapping dots for darker text
    # Double-strike is different from bold - produces overlapping character dots
    - service: test_double_strike
      then:
        - esphome.thermalprinter_print_text:
            text_to_print: "=== Double-Strike Test ==="
            alignment: 1
        - esphome.thermalprinter_print_text:
            text_to_print: "Normal text: HELLO WORLD"
            double_strike: false
        - esphome.thermalprinter_print_text:
            text_to_print: "Double-strike: HELLO WORLD"
            double_strike: true
        - esphome.thermalprinter_print_text:
            text_to_print: "Bold text: HELLO WORLD"
            bold: true
        - esphome.thermalprinter_print_text:
            text_to_print: "Bold + Double-strike: HELLO WORLD"
            bold: true
            double_strike: true
        - esphome.thermalprinter_print_text:
            text_to_print: "Test complete - formatting reset"

    # Left spacing test service
    # Tests left spacing control (ESC B command) - adds spacing to left side
    - service: test_left_spacing
      then:
        - esphome.thermalprinter_print_text:
            text_to_print: "=== Left Spacing Test ==="
            alignment: 1
        # Print without spacing (default)
        - esphome.thermalprinter_print_text:
            text_to_print: "No spacing: This text starts at the normal left position."
        # Set left spacing to 10 dots
        - m5stack_printer.set_left_spacing:
            spacing_dots: 10
        - esphome.thermalprinter_print_text:
            text_to_print: "Left spacing 10: This text should be indented 10 dots from the left."
        # Set larger left spacing (30 dots)
        - m5stack_printer.set_left_spacing:
            spacing_dots: 30
        - esphome.thermalprinter_print_text:
            text_to_print: "Left spacing 30: This text should be significantly indented from the left."
        # Test maximum spacing (47 dots)
        - m5stack_printer.set_left_spacing:
            spacing_dots: 47
        - esphome.thermalprinter_print_text:
            text_to_print: "Max spacing 47: This shows the maximum left spacing supported."
        # Reset spacing to default
        - m5stack_printer.reset_left_spacing:
        - esphome.thermalprinter_print_text:
            text_to_print: "Spacing reset: Back to normal left position."

    # Printer settings services  
    - service: set_printer_settings
      variables:
        line_spacing: int
        print_density: int
        break_time: int
      then:
        - esphome.set_printer_settings:
            id: printer
            line_spacing: !lambda "return line_spacing;"
            print_density: !lambda "return print_density;"
            break_time: !lambda "return break_time;"

    - service: reset_printer_settings
      then:
        - esphome.reset_printer_settings:
            id: printer
    # Cut paper with optional feeding (requires printer with cutting mechanism)
    # cut_mode: 0=full cut (ESC i), 1=partial cut (GS V 1), 66=cut with feed (GS V 66)
    # feed_lines: Additional lines to feed before cutting (0-255, only used with mode 66)
    - service: cut_paper
      variables:
        cut_mode: int
        feed_lines: int
      then:
        - m5stack_printer.cut_paper:
            cut_mode: !lambda "return cut_mode;"
            feed_lines: !lambda "return feed_lines;"
    # Set text alignment for subsequent text printing
    # alignment: 0=left aligned, 1=center aligned, 2=right aligned
    - service: set_alignment
      variables:
        alignment: int
      then:
        - m5stack_printer.set_alignment:
            alignment: !lambda "return alignment;"
    # Set text styling modes without printing (styles persist until changed)
    # bold: Enable bold/emphasized text (true/false)
    # underline: Underline mode (0=off, 1=single 1-dot line, 2=double 2-dot line)
    # upside_down: Rotate individual characters 180 degrees (true/false)
    # rotation: Enable 90-degree clockwise rotation of entire text (true/false)
    # inverse: Enable white text on black background printing (true/false)
    # chinese_mode: Enable processing of multi-byte Asian characters (true/false)
    # line_spacing: Custom line spacing in dots (0-255, ESC 3 command)
    # print_density: Print heat density (0-31, higher=darker but slower, affects print head life)
    # break_time: Break time between printed dots (0-7, microsecond units, balances speed vs quality)
    - service: set_text_style
      variables:
        bold: bool
        underline: int
        upside_down: bool
        font_type: int
        rotation: bool
        inverse: bool
        chinese_mode: bool
        line_spacing: int
        print_density: int
        break_time: int
      then:
        - m5stack_printer.set_text_style:
            bold: !lambda "return bold;"
            underline: !lambda "return underline;"
            upside_down: !lambda "return upside_down;"
            font_type: !lambda "return font_type;"
        - m5stack_printer.set_90_degree_rotation:
            enable: !lambda "return rotation;"
        - m5stack_printer.set_inverse_printing:
            enable: !lambda "return inverse;"
        - m5stack_printer.set_chinese_mode:
            enable: !lambda "return chinese_mode;"
        - m5stack_printer.set_line_spacing:
            spacing: !lambda "return line_spacing;"
        - m5stack_printer.set_print_density:
            density: !lambda "return print_density;"
            break_time: !lambda "return break_time;"
    # Print built-in test page (no parameters, prints printer diagnostics and sample patterns)
    - service: print_test_page
      then:
        - m5stack_printer.print_test_page
    # Run comprehensive demo showcasing printer capabilities with Hitchhiker's Guide theme
    # All parameters are optional and default to true - call without any parameters to run full demo
    # show_qr_code: Include QR code examples in demo (default: true)
    # show_barcode: Include various barcode format examples (default: true)
    # show_text_styles: Include bold, underline, sizing demonstrations (default: true)
    # show_inverse: Include white-on-black text examples (default: true)
    # show_rotation: Include 90-degree rotated text examples (default: true)
    - service: run_demo
      variables:
        show_qr_code: bool
        show_barcode: bool
        show_text_styles: bool
        show_inverse: bool
        show_rotation: bool
      then:
        - m5stack_printer.run_demo:
            show_qr_code: !lambda "return show_qr_code;"
            show_barcode: !lambda "return show_barcode;"
            show_text_styles: !lambda "return show_text_styles;"
            show_inverse: !lambda "return show_inverse;"
            show_rotation: !lambda "return show_rotation;"
    # Set horizontal tab stop positions for tabular formatting (ESC D command)
    # positions: Comma or space separated character positions (e.g., "8,16,24,32" or "10 20 30")
    # Maximum 32 tab stops, positions are in character widths from left margin
    - service: set_tab_positions
      variables:
        positions: string
      then:
        - m5stack_printer.set_tab_positions:
            positions: !lambda "return positions;"
    # Jump to next horizontal tab position (HT/0x09 command, no parameters)
    # Use after setting tab positions with set_tab_positions service
    # If no tab positions set or past last tab, moves to next 8-character boundary
    - service: horizontal_tab
      then:
        - m5stack_printer.horizontal_tab
    # Set absolute horizontal print position from left margin (ESC $ command)
    # position: Horizontal position in dots from left margin (0-383 for 58mm paper)
    # Useful for precise alignment, right-justifying text, or creating custom layouts
    - service: set_horizontal_position
      variables:
        position: int
      then:
        - m5stack_printer.set_horizontal_position:
            position: !lambda "return position;"

    # Send raw ESC/POS command bytes for debugging
    # command: Comma-separated byte values (e.g., "27,69,1" for ESC E 1)
    # Use this to test specific ESC/POS commands and find what works with your printer
    # Examples:
    #   Bold on: "27,69,1"         Bold off: "27,69,0"
    #   Underline on: "27,45,1"    Underline off: "27,45,0"
    #   Align center: "27,97,1"    Align left: "27,97,0"
    #   Inverse on: "29,66,1"      Inverse off: "29,66,0"
    - service: send_raw_command
      variables:
        command: string
      then:
        - m5stack_printer.send_raw_command:
            command: !lambda "return command;"

# Enable OTA updates
ota:
  - platform: esphome
    password: !secret OTA_password

# Enable WiFi
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Thermalprinter Fallback Hotspot"
    password: !secret fallback_hotspot_password

captive_portal:

external_components:
  # m5stack_printer debug - local development version
  - source: components/
    components: [m5stack_printer]
  # GitHub version (for production):
  # - source: github://jeroenterheerdt/esphome-components-jesse #@jesserockz-2025-036
  #   components: [m5stack_printer]
  #   refresh: 0s

uart:
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 9600

display:
  platform: m5stack_printer
  id: printer
  height: 50
  auto_clear_enabled: false
